"""refactor delivery fee and subtotal

Revision ID: 10481482ac2c
Revises: 21c801f9e0f0
Create Date: 2026-07-16 13:58:30.765088

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "10481482ac2c"
down_revision: Union[str, Sequence[str], None] = "21c801f9e0f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "orders",
        sa.Column("subtotal", sa.Numeric(10, 2), nullable=True),
    )

    op.execute("""
        UPDATE orders
        SET subtotal = total_amount - delivery_fee
    """)

    op.alter_column(
        "orders",
        "subtotal",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "subtotal")
    # ### end Alembic commands ###
