"""refactor listing categories

Revision ID: 52b7c7dabf0a
Revises: c72ee0263ee4
Create Date: 2026-07-14 09:59:26.424386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b7c7dabf0a'
down_revision: Union[str, Sequence[str], None] = 'c72ee0263ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.add_column('listings', sa.Column('category_id', sa.UUID(), nullable=False))
    op.add_column('listings', sa.Column('gender', sa.Enum('men', 'women', 'unisex', 'kids', name='gender', native_enum=False), nullable=False))
    op.add_column('listings', sa.Column('is_thrift', sa.Boolean(), nullable=False))
    op.add_column('listings', sa.Column('is_on_sale', sa.Boolean(), nullable=False))
    op.alter_column('listings', 'condition',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.create_foreign_key(None, 'listings', 'categories', ['category_id'], ['id'])
    op.drop_column('listings', 'section')
    op.drop_column('listings', 'category')
    op.create_unique_constraint('uq_buyer_listing', 'wishlists', ['buyer_id', 'listing_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_buyer_listing', 'wishlists', type_='unique')
    op.add_column('listings', sa.Column('category', sa.VARCHAR(length=11), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('section', sa.VARCHAR(length=7), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.alter_column('listings', 'condition',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.drop_column('listings', 'is_on_sale')
    op.drop_column('listings', 'is_thrift')
    op.drop_column('listings', 'gender')
    op.drop_column('listings', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
