"""add seller_type to seller profiles

Revision ID: 60be38514f92
Revises: a37002d87468
Create Date: 2026-06-14 12:29:05.671481

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "60be38514f92"
down_revision: Union[str, Sequence[str], None] = "a37002d87468"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    seller_type = sa.Enum("thrift", "surplus", name="sellertype")

    seller_type.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "seller_profiles",
        sa.Column(
            "seller_type",
            seller_type,
            nullable=False,
            server_default="thrift",
        ),
    )
    op.drop_column("seller_profiles", "id_document_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "seller_profiles",
        sa.Column(
            "id_document_url",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("seller_profiles", "seller_type")
    # ### end Alembic commands ###
