"""add quantity to listings

Revision ID: 6b77f2f428d8
Revises: 958c83e978fa
Create Date: 2026-07-08 11:35:32.974367

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6b77f2f428d8"
down_revision: Union[str, Sequence[str], None] = "958c83e978fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "listings",
        sa.Column("quantity", sa.Integer(), nullable=False, server_default="1"),
    )
    op.alter_column("listings", "quantity", server_default=None)
    op.drop_column("listings", "is_boosted")
    op.drop_column("listings", "boost_expires_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "listings",
        sa.Column(
            "boost_expires_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "listings",
        sa.Column("is_boosted", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("listings", "quantity")
    # ### end Alembic commands ###
