"""add listing color

Revision ID: 6c6fa4797fce
Revises: 52b7c7dabf0a
Create Date: 2026-07-14 11:31:25.707020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c6fa4797fce'
down_revision: Union[str, Sequence[str], None] = '52b7c7dabf0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('color', sa.Enum('black', 'white', 'red', 'blue', 'green', 'yellow', 'purple', 'pink', 'brown', 'gray', 'maroon', 'navy', 'beige', name='listingcolor', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'color')
    # ### end Alembic commands ###
