"""Add clearance and surplus flags to listings

Revision ID: 6defc02ac4ad
Revises: beea863050f1
Create Date: 2026-07-18 16:23:10.511389

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6defc02ac4ad"
down_revision: Union[str, Sequence[str], None] = "beea863050f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ✅ Add columns with server_default
    op.add_column(
        "listings",
        sa.Column("is_clearance", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "listings",
        sa.Column("is_surplus", sa.Boolean(), server_default="false", nullable=False),
    )

    # ✅ Skip the enum change for now - handle separately if needed
    # The seller_type column might already be VARCHAR, so just update the data
    op.execute(
        "UPDATE seller_profiles SET seller_type = 'retailer' WHERE seller_type = 'surplus'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "seller_profiles",
        "seller_type",
        existing_type=sa.Enum(
            "thrift", "retailer", name="sellertype", native_enum=False
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "listings",
        "is_clearance",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.drop_column("listings", "is_surplus")
    # ### end Alembic commands ###
