"""remove is_thrift flag

Revision ID: 6f43e38d2297
Revises: 9232b7639ac3
Create Date: 2026-07-15 10:15:28.667600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f43e38d2297'
down_revision: Union[str, Sequence[str], None] = '9232b7639ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'is_thrift')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('is_thrift', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
