"""listing condition as nullable

Revision ID: 9232b7639ac3
Revises: 6c6fa4797fce
Create Date: 2026-07-15 10:05:57.743621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9232b7639ac3'
down_revision: Union[str, Sequence[str], None] = '6c6fa4797fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'size',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('listings', 'condition',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'condition',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('listings', 'size',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    # ### end Alembic commands ###
