"""replace delivery_method with payment and phone snapshots

Revision ID: 958c83e978fa
Revises: e59af25c5826
Create Date: 2026-07-05 10:19:29.387703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958c83e978fa'
down_revision: Union[str, Sequence[str], None] = 'e59af25c5826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('receiver_phone', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('payment_method', sa.Enum('esewa', 'khalti', 'cod', name='paymentmethod', native_enum=False), nullable=False))
    op.drop_column('orders', 'delivery_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_method', sa.VARCHAR(length=7), autoincrement=False, nullable=False))
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'receiver_phone')
    # ### end Alembic commands ###
