"""Remove clearance tag

Revision ID: ba36a01bdfef
Revises: 6defc02ac4ad
Create Date: 2026-07-18 18:30:37.700458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba36a01bdfef'
down_revision: Union[str, Sequence[str], None] = '6defc02ac4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'is_surplus',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('listings', 'is_clearance')
    op.alter_column('seller_profiles', 'seller_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('retailer', 'thrift', name='sellertype', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller_profiles', 'seller_type',
               existing_type=sa.Enum('retailer', 'thrift', name='sellertype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.add_column('listings', sa.Column('is_clearance', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.alter_column('listings', 'is_surplus',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
