"""Fix review unique constraint

Revision ID: beea863050f1
Revises: 455ab4c2fc4b
Create Date: 2026-07-18 11:03:49.796551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beea863050f1'
down_revision: Union[str, Sequence[str], None] = '455ab4c2fc4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reviews_listing_id_key'), 'reviews', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('reviews_listing_id_key'), 'reviews', ['listing_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
