"""add indexes to listings for status, category, seller, created_at

Revision ID: d254f34ee080
Revises: 1c690b7d30ab
Create Date: 2026-08-03 11:14:12.727073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd254f34ee080'
down_revision: Union[str, Sequence[str], None] = '1c690b7d30ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('email_verifications_token_key'), 'email_verifications', type_='unique')
    op.drop_index(op.f('ix_email_verifications_token'), table_name='email_verifications')
    op.create_index(op.f('ix_email_verifications_token'), 'email_verifications', ['token'], unique=True)
    op.create_index('ix_listings_category_id', 'listings', ['category_id'], unique=False)
    op.create_index('ix_listings_created_at', 'listings', ['created_at'], unique=False)
    op.create_index('ix_listings_seller_id', 'listings', ['seller_id'], unique=False)
    op.create_index('ix_listings_status', 'listings', ['status'], unique=False)
    op.create_index('ix_listings_status_created_at', 'listings', ['status', 'created_at'], unique=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('pending', 'accepted', 'rejected', 'cancelled', 'ready_for_pickup', 'picked_up', 'out_for_delivery', 'delivered', 'completed', name='orderstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('seller_profiles', 'seller_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('thrift_shop', 'retail_shop', name='sellertype', native_enum=False),
               existing_nullable=False)
    op.alter_column('seller_profiles', 'is_identity_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('seller_profiles', 'is_business_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('seller_profiles', 'business_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('registered', 'unregistered', name='businesstype', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'individual'::character varying"))
    op.alter_column('seller_profiles', 'applied_as_business',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('seller_profiles', 'business_address_proof')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_profiles', sa.Column('business_address_proof', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('seller_profiles', 'applied_as_business',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('seller_profiles', 'business_type',
               existing_type=sa.Enum('registered', 'unregistered', name='businesstype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'individual'::character varying"))
    op.alter_column('seller_profiles', 'is_business_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('seller_profiles', 'is_identity_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('seller_profiles', 'seller_type',
               existing_type=sa.Enum('thrift_shop', 'retail_shop', name='sellertype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('pending', 'accepted', 'rejected', 'cancelled', 'ready_for_pickup', 'picked_up', 'out_for_delivery', 'delivered', 'completed', name='orderstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index('ix_listings_status_created_at', table_name='listings')
    op.drop_index('ix_listings_status', table_name='listings')
    op.drop_index('ix_listings_seller_id', table_name='listings')
    op.drop_index('ix_listings_created_at', table_name='listings')
    op.drop_index('ix_listings_category_id', table_name='listings')
    op.drop_index(op.f('ix_email_verifications_token'), table_name='email_verifications')
    op.create_index(op.f('ix_email_verifications_token'), 'email_verifications', ['token'], unique=False)
    op.create_unique_constraint(op.f('email_verifications_token_key'), 'email_verifications', ['token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
